[package]
name = "qrbadge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minidom = "*"
qrcode = "0.12.0"
image = "0.23.14"
structopt = "0.3.13"
